name: CI
on:
  pull_request:
    branches:
      - 'dev'
    paths-ignore:
      - '**.md'
  push:
    branches:
      - 'dev'
    paths-ignore:
      - '**.md'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run style check
        run: ./gradlew ktlintCheck

      - name: Run tests
        run: ./gradlew testDebug