name: CI
on:
  pull_request:
    branches:
      - 'dev'
    paths-ignore:
      - '**.md'
  push:
    branches:
      - 'dev'
    paths-ignore:
      - '**.md'
jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run style check
        run: ./gradlew ktlintCheck

      - name: Run tests
        run: ./gradlew testDebug --stacktrace

  android_tests:
    runs-on: macos-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        api-level: [19, 28, 29]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86
          disable-animations: true
          script: ./gradlew app:connectedDebugAndroidTest --stacktrace

      - name: Upload tests results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: android_tests_results
          path: app/build/reports/androidTests/connected