name: CI
on:
  pull_request:
    branches:
      - 'dev'
    paths-ignore:
      - '**.md'
  push:
    branches:
      - 'dev'
    paths-ignore:
      - '**.md'
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run style check
        run: ./gradlew ktlintCheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: ./gradlew testDebug

  android_tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedDebugAndroidTest